package virtualkey

import (
	"fmt"
	"strings"

	"github.com/your-org/ai-runtime-gateway/internal/core"
)

const legacySecretLength = 43 // 32 random bytes encoded with base64.RawURLEncoding

type PresentedKey struct{ Environment, PublicID, Secret string }

// Parse accepts the unambiguous v2 form:
//
//	zg_<environment>_<public-id>.<secret>
//
// It also accepts the original underscore-only form generated by early
// development builds. Legacy parsing uses the fixed 43-character secret
// length instead of splitting on underscores, because both public IDs and
// base64url secrets may themselves contain underscores.
func Parse(raw string) (PresentedKey, error) {
	raw = strings.TrimSpace(raw)
	if !strings.HasPrefix(raw, "zg_") {
		return PresentedKey{}, malformedKey()
	}
	remainder := strings.TrimPrefix(raw, "zg_")
	environment, payload, ok := strings.Cut(remainder, "_")
	if !ok || environment == "" || payload == "" {
		return PresentedKey{}, malformedKey()
	}

	if publicID, secret, found := strings.Cut(payload, "."); found {
		if !validKeyParts(publicID, secret) {
			return PresentedKey{}, malformedKey()
		}
		return PresentedKey{Environment: environment, PublicID: publicID, Secret: secret}, nil
	}

	if len(payload) <= legacySecretLength || payload[len(payload)-legacySecretLength-1] != '_' {
		return PresentedKey{}, malformedKey()
	}
	publicID := payload[:len(payload)-legacySecretLength-1]
	secret := payload[len(payload)-legacySecretLength:]
	if !validKeyParts(publicID, secret) {
		return PresentedKey{}, malformedKey()
	}
	return PresentedKey{Environment: environment, PublicID: publicID, Secret: secret}, nil
}

func validKeyParts(publicID, secret string) bool {
	return strings.TrimSpace(publicID) == publicID && publicID != "" &&
		strings.TrimSpace(secret) == secret && len(secret) >= 16 &&
		!strings.Contains(publicID, ".") && !strings.Contains(secret, ".")
}

func malformedKey() error {
	return fmt.Errorf("%w: malformed virtual key", core.ErrUnauthorized)
}
